const unit_conversions = (
    "Ohm"    => "Ω",          "Ω" => "Ohm",
    "deg"    => "°",          "°" => "deg",
    "arcmin" => "arcminute",  "arcminute" => "arcmin",
    "arscec" => "arcsecond",  "arcsecond" => "arcsec",
    "min"    => "minute",     "minute" => "min",
    "h" => "hr",              "hr" => "h",
    "a" => "yr",              "yr" => "a",
    "solMass" => "Msun",      "Msun" => "solMass",
    "Angstrom" => "angstrom", "angstrom" => "Angstrom",
    "solRad" => "Rsun",       "Rsun" => "solRad",
    "lyr" => "ly",            "ly" => "lyr",
    # "count" => "",          "" => "count",
    # "ct" => "",             "" => "ct",
    # "photon" => "",         "" => "photon",
    # "ph" => "",             "" => "ph",
    # "R" => "Rayleigh",      "Rayleigh" => "R",
    "G" => "Gauss",           "Gauss" => "G",
    # "pixel" => "pix",       "pix" => "pixel",
    # "pix" => "pix",         "pix" => "pix",
    # "barn" => "barn",       "barn" => "barn",
    # "D" => "debye",         "debye" => "D",
    # "chan" => "",           "" => "chan",
    # "bin => "",             "" => "bin",
    # "voxel" => "",          "" => "voxel",
    # "bit" => "",            "" => "bit",
    # "byte" => "",           "" => "byte",
    # "adu" => "",            "" => "adu",
    # "beam" => "",           "" => "beam"
)
